name: 华尔街见闻日历同步

on:
  schedule:
    # 每周一0点执行 (UTC时间，对应北京时间周一8点)
    - cron: '0 16 * * 0'  # UTC时间周日16点，对应北京时间周一0点
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 确保输出目录存在
      run: mkdir -p calendar_files
        
    - name: 获取日历数据并生成ICS文件
      run: python fetch_calendar.py
      env:
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
        COS_REGION: ${{ secrets.COS_REGION }}
        COS_BUCKET: ${{ secrets.COS_BUCKET }}
        COS_OBJECT_KEY: ${{ secrets.COS_OBJECT_KEY }}
        
    - name: 检查ICS文件是否生成
      run: |
        if [ -f "calendar_files/wsc_events.ics" ]; then
          echo "ICS文件已成功生成"
        else
          echo "警告：ICS文件未生成，将创建一个空文件用于上传测试"
          mkdir -p calendar_files
          touch calendar_files/wsc_events.ics
          echo "BEGIN:VCALENDAR\nVERSION:2.0\nEND:VCALENDAR" > calendar_files/wsc_events.ics
        fi
        
    - name: 保存ICS文件为工作流程构件
      uses: actions/upload-artifact@v2  # 降级到v2版本
      with:
        name: calendar-files
        path: calendar_files/wsc_events.ics
        if-no-files-found: warn  # 如果没有找到文件，发出警告但不会失败 