name: 华尔街见闻日历同步

on:
  schedule:
    # 每周一0点执行 (UTC时间，对应北京时间周一8点)
    - cron: '0 16 * * 0'  # UTC时间周日16点，对应北京时间周一0点
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: 确保输出目录存在
      run: |
        mkdir -p calendar_files
        mkdir -p logs
        
    - name: 获取全球日历数据并生成ICS文件
      run: python src/core/fetch_calendar.py
      env:
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
        COS_REGION: ${{ secrets.COS_REGION }}
        COS_BUCKET: ${{ secrets.COS_BUCKET }}
        COS_OBJECT_KEY: ${{ secrets.COS_OBJECT_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
    - name: 获取中国日历数据并生成ICS文件
      run: python src/core/fetch_china_calendar.py
      env:
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
        COS_REGION: ${{ secrets.COS_REGION }}
        COS_BUCKET: ${{ secrets.COS_BUCKET }}
        COS_OBJECT_KEY_CHINA: ${{ secrets.COS_OBJECT_KEY_CHINA || 'calendar/wsc_china_events.ics' }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
    - name: 检查全球日历ICS文件是否生成和上传
      run: |
        if [ -f "calendar_files/wsc_events.ics" ]; then
          echo "全球日历ICS文件已成功生成"
          # 在工作流日志中显示ICS文件内容，方便在GitHub查看
          echo "========================= 全球日历ICS文件内容 ========================="
          cat calendar_files/wsc_events.ics
          echo "================================================================"
          echo "文件已生成并可能已上传至腾讯云COS，请查看上方日志了解详情"
        else
          echo "警告：全球日历ICS文件未生成"
          exit 1
        fi
        
    - name: 检查中国日历ICS文件是否生成和上传
      run: |
        if [ -f "calendar_files/wsc_china_events.ics" ]; then
          echo "中国日历ICS文件已成功生成"
          # 在工作流日志中显示ICS文件内容，方便在GitHub查看
          echo "========================= 中国日历ICS文件内容 ========================="
          cat calendar_files/wsc_china_events.ics
          echo "================================================================"
          echo "文件已生成并可能已上传至腾讯云COS，请查看上方日志了解详情"
        else
          echo "警告：中国日历ICS文件未生成"
          exit 1
        fi 